# LLM 기본 설정 파일
# 모든 환경에서 공통으로 사용되는 기본값

llm:
  default_model: "claude-3-5-haiku-20241022"
  available_models:
    - "claude-3-5-haiku-20241022"
    - "claude-3-5-sonnet-20241022"
    - "claude-3-opus-20240229"
    - "claude-3-haiku-20240307"
  
  tasks:
    classification:
      model: "claude-3-5-haiku-20241022"
      max_tokens: 300
      temperature: 0.3
      confidence: 0.5
    
    sql_generation:
      model: "claude-3-5-haiku-20241022"
      max_tokens: 1200
      temperature: 0.1
      confidence: 0.8
    
    data_analysis:
      model: "claude-3-5-haiku-20241022"
      max_tokens: 1200
      temperature: 0.7
    
    guide_generation:
      model: "claude-3-5-haiku-20241022"
      max_tokens: 800
      temperature: 0.7
    
    out_of_scope:
      model: "claude-3-5-haiku-20241022"
      max_tokens: 400
      temperature: 0.5