steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - update_metadata_cache
      - --gen2
      - --runtime=python311  # Python 3.11 사용
      - --source=.
      - --entry-point=update_metadata_cache
      - --trigger-http
      - --region=asia-northeast3
      - --memory=1024MB
      - --timeout=540s
      - --set-env-vars=GOOGLE_CLOUD_PROJECT=${PROJECT_ID},TARGET_TABLE_ID=nlq-ex.test_dataset.events_20210131,GCS_BUCKET=nlq-metadata-cache
      - --service-account=${PROJECT_NUMBER}-compute@developer.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY